spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
    topic:
      order-events: order-topic
      inventory-events: inventory-topic
