auth_enabled: false
server:
  http_listen_port: 3100
  grpc_listen_port: 9095
ingester:
  wal:
    dir: "/loki/wal"  # WAL directory for local storage
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  chunk_target_size: 1536000
  chunk_block_size: 262144

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem  # Use local filesystem for storage
      schema: v12  # Use v12 instead of v13, or remove this line if using auto schema detection
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /loki/storage  # Local directory for logs and data

compactor:
  working_directory: /loki/compactor  # Local compactor directory

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules  # Directory for storing rules
  rule_path: /loki/rules  # Local path for rules
  ring:
    kvstore:
      store: inmemory
  enable_api: true
