spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project
    username: root
    password: DragonBOSS20
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    topic: order-events

